package com.forrestlasiter.umbra.net.dns

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * Conformance: the Kotlin DNS builder must produce the exact bytes in the shared
 * golden vectors (spec/datapath-vectors.json, generated by the Python reference).
 * This pins the Android port to the same wire format as the Linux/iOS sides.
 */
class DatapathVectorsTest {

    @Test fun blocked_responses_match_the_golden_vectors() {
        val text = javaClass.getResourceAsStream("/datapath-vectors.json")!!
            .bufferedReader().readText()
        val vectors = Json.parseToJsonElement(text).jsonObject["dns_blocked_responses"]!!.jsonArray
        assert(vectors.size >= 4)
        for (v in vectors) {
            val o = v.jsonObject
            val name = o["name"]!!.jsonPrimitive.content
            val query = hexToBytes(o["query_hex"]!!.jsonPrimitive.content)
            val expected = o["response_hex"]!!.jsonPrimitive.content
            val response = DnsQuery.parse(query)!!.buildBlockedResponse()
            assertEquals("response mismatch for $name", expected, bytesToHex(response))
        }
    }

    private fun hexToBytes(hex: String): ByteArray =
        ByteArray(hex.length / 2) { ((hex[it * 2].digitToInt(16) shl 4) or hex[it * 2 + 1].digitToInt(16)).toByte() }

    private fun bytesToHex(bytes: ByteArray): String =
        bytes.joinToString("") { "%02x".format(it) }
}
