import XCTest
@testable import UmbraCore

/// Conformance: the Swift DNS builder must produce the exact bytes in the shared
/// golden vectors (spec/datapath-vectors.json, generated by the Python reference)
/// — pinning the iOS port to the same wire format as the Linux/Android sides.
final class DatapathVectorsTests: XCTestCase {

    private struct Vector: Codable {
        let name: String; let qtype: Int; let query_hex: String; let response_hex: String
    }
    private struct Blocklist: Codable {
        let domains: [String]
        let cases: [Case]
        struct Case: Codable { let name: String; let blocked: Bool }
    }
    private struct Doc: Codable {
        let dns_blocked_responses: [Vector]
        let blocklist: Blocklist
    }

    private func loadDoc() throws -> Doc {
        let url = try XCTUnwrap(Bundle.module.url(forResource: "datapath-vectors", withExtension: "json"))
        return try JSONDecoder().decode(Doc.self, from: Data(contentsOf: url))
    }

    func testBlockedResponsesMatchGoldenVectors() throws {
        let doc = try loadDoc()
        XCTAssertGreaterThanOrEqual(doc.dns_blocked_responses.count, 4)
        for v in doc.dns_blocked_responses {
            let query = [UInt8](hex: v.query_hex)
            let response = DnsQuery.parse(query)!.buildBlockedResponse()
            XCTAssertEqual(response.hexString, v.response_hex, v.name)
        }
    }

    func testBlocklistMatchingMatchesGoldenVectors() throws {
        let doc = try loadDoc()
        let list = TelemetryBlocklist(Set(doc.blocklist.domains))
        for c in doc.blocklist.cases {
            XCTAssertEqual(list.isBlocked(c.name), c.blocked, c.name)
        }
    }
}

private extension Array where Element == UInt8 {
    init(hex: String) {
        var bytes = [UInt8]()
        var idx = hex.startIndex
        while idx < hex.endIndex {
            let next = hex.index(idx, offsetBy: 2)
            bytes.append(UInt8(hex[idx..<next], radix: 16)!)
            idx = next
        }
        self = bytes
    }
    var hexString: String { map { String(format: "%02x", $0) }.joined() }
}
